name: Armies
version: '${project.version}'
main: me.rownox.armies.Armies
api-version: 1.19
depend:
  - Vault
  - Essentials
commands:
  kit:
    usage: "/kit <player>"
  shop:
    usage: "/shop"
  discord:
    usage: "/discord"
  help:
    usage: "/help"
